### ISSUE TITLE
Trailing command is lost

### ISSUE THREAD

**Issue by Jamminroot** [andyjohnson0/TakeoutExtractor#16]
https://github.com/andyjohnson0/TakeoutExtractor/blob/cdd34d41b4303b84dc0b43985cfbf190ae55e566/TakeoutExtractor.Cli/CommandLine.cs#L58C26-L58C26

Trailing command is lost

```diff
                if (commands.Contains(arg))
                {
                    currentCommand = arg;
+                   commandToArgs.Add(currentCommand, new List<string>());
                }
```

**Comment by andyjohnson0** [comment]
Fixed in v1.1. Thanks to @Jamminroot for reporting this.
