### ISSUE TITLE
Error on arrays

### ISSUE THREAD

**Issue by Jamminroot** [andyjohnson0/TakeoutExtractor#17]
https://github.com/andyjohnson0/TakeoutExtractor/blob/cdd34d41b4303b84dc0b43985cfbf190ae55e566/TakeoutExtractor.Lib/Photo/PhotoMetadata.cs#L74

Error on arrays

```diff
- md.title = elem.GetString()!;
+ md.title = elem.ValueKind == JsonValueKind.Array ? elem[0].GetString()! : elem.GetString()!;
```

**Comment by andyjohnson0** [comment]
Fixed in v1.1. Thanks to @Jamminroot for reporting this.
