### ISSUE TITLE
GUI is not longer (easy) installable

### ISSUE THREAD

**Issue by ranseyer** [andyjohnson0/TakeoutExtractor#18]
Under Windows 11 is not longer easy possible to install the GUI. I Think reason is that your certificate is only valid until July...

![image](https://github.com/andyjohnson0/TakeoutExtractor/assets/3889328/8dc096e4-b4f5-4301-bb9f-2640b2e562bc)

**Comment by andyjohnson0** [comment]
Fixed in v1.1. Thanks to @ranseyer for reporting this.
